0.91/0.11	I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
0.91/0.11	I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
0.91/0.11	I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
0.91/0.11	I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
0.91/0.11	I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
1.62/0.86	hyperparameter optimization for tensorflow is being started
1.62/0.86	Params: {'conv2_depth': '476', 'fc_depth': '469', 'conv1_depth': '16', 'filter_size': '12'}
1.92/1.19	Traceback (most recent call last):
1.92/1.19	  File "/root/tf-hpolib/tf-hpo/src/hpolib-main.py", line 42, in <module>
1.92/1.19	    result = main(params, **args)
1.92/1.19	  File "/root/tf-hpolib/tf-hpo/src/hpolib-main.py", line 31, in main
1.92/1.19	    logger.create(['Filter size', 'Conv1 depth', 'Conv2 depth', 'FC neurons'], ['Test Accuracy', 'Validation Accuarcy', 'Training Accuracy'])  
1.92/1.19	  File "/root/tf-hpolib/tf-hpo/src/modules/logger.py", line 57, in create
1.92/1.19	    fileHandler = logging.FileHandler(self.path)
1.92/1.19	  File "/usr/lib/python2.7/logging/__init__.py", line 903, in __init__
1.92/1.19	    StreamHandler.__init__(self, self._open())
1.92/1.19	  File "/usr/lib/python2.7/logging/__init__.py", line 928, in _open
1.92/1.19	    stream = open(self.baseFilename, self.mode)
1.92/1.19	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
2.01/1.22	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7fac797223b0>> ignored
