0.94/0.10	I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
0.94/0.10	I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
0.94/0.10	I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
0.94/0.10	I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
0.94/0.10	I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
1.63/0.85	hyperparameter optimization for tensorflow is being started
1.63/0.85	Params: {'conv2_depth': '1', 'fc_depth': '1', 'conv1_depth': '1', 'filter_size': '1'}
1.80/18.53	('Successfully downloaded', 'train-images-idx3-ubyte.gz', 9912422, 'bytes.')
1.81/19.42	('Successfully downloaded', 'train-labels-idx1-ubyte.gz', 28881, 'bytes.')
1.83/23.39	('Successfully downloaded', 't10k-images-idx3-ubyte.gz', 1648877, 'bytes.')
1.83/23.83	('Successfully downloaded', 't10k-labels-idx1-ubyte.gz', 4542, 'bytes.')
2.20/24.29	Traceback (most recent call last):
2.20/24.29	  File "/root/tf-hpolib/tf-hpo/src/hpolib-main.py", line 42, in <module>
2.20/24.29	    result = main(params, **args)
2.20/24.29	  File "/root/tf-hpolib/tf-hpo/src/hpolib-main.py", line 32, in main
2.20/24.29	    print("Logging test errors at " + OUTPUT_LOG_PATH)        
2.20/24.29	NameError: global name 'OUTPUT_LOG_PATH' is not defined
