0.93/0.11	I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
0.93/0.11	I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
0.93/0.11	I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
0.93/0.11	I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
0.93/0.11	I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
1.63/0.85	hyperparameter optimization for tensorflow is being started
1.63/0.85	Params: {'conv2_depth': '257', 'fc_depth': '321', 'conv1_depth': '362', 'filter_size': '3'}
1.92/1.18	Traceback (most recent call last):
1.92/1.18	  File "/root/tf-hpolib/tf-hpo/src/hpolib-main.py", line 42, in <module>
1.92/1.18	    result = main(params, **args)
1.92/1.18	  File "/root/tf-hpolib/tf-hpo/src/hpolib-main.py", line 32, in main
1.92/1.18	    print("Logging test errors at " + OUTPUT_LOG_PATH)        
1.92/1.18	NameError: global name 'OUTPUT_LOG_PATH' is not defined
