0.92/0.12	I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
0.92/0.12	I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
0.92/0.12	I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
0.92/0.12	I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
0.92/0.12	I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
1.63/0.82	hyperparameter optimization for tensorflow is being started
1.63/0.82	Params: {'conv2_depth': '307', 'fc_depth': '49', 'conv1_depth': '13', 'filter_size': '13'}
1.93/1.15	Traceback (most recent call last):
1.93/1.15	  File "/root/tf-hpolib/tf-hpo/src/hpolib-main.py", line 42, in <module>
1.93/1.15	    result = main(params, **args)
1.93/1.15	  File "/root/tf-hpolib/tf-hpo/src/hpolib-main.py", line 32, in main
1.93/1.15	    print("Logging test errors at " + LOG_PATH)        
1.93/1.15	NameError: global name 'OUTPUT_LOG_PATH' is not defined
