0.85/0.14	I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
0.85/0.15	I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
0.85/0.15	I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
0.85/0.15	I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
0.85/0.15	I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
1.43/0.69	tensorflow CNN code started
1.43/0.69	Params: {'conv2_depth': '186.0', 'fc_depth': '452.0', 'conv1_depth': '134.0', 'filter_size': '9.0'}
1.83/1.05	Traceback (most recent call last):
1.83/1.05	  File "../convolutional-hpolib.py", line 385, in <module>
1.83/1.05	    result = main(params, **args)
1.83/1.05	  File "../convolutional-hpolib.py", line 376, in main
1.83/1.05	    y = train_mnist(dataset, flags)
1.83/1.05	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.83/1.05	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.83/1.05	ValueError: invalid literal for int() with base 10: '9.0'
