0.92/0.12	I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
0.92/0.13	I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
0.92/0.13	I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
0.92/0.13	I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
0.92/0.13	I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
1.43/0.66	tensorflow CNN code started
1.43/0.66	Params: {'conv2_depth': '392.0', 'fc_depth': '485.0', 'conv1_depth': '146.0', 'filter_size': '8.0'}
1.64/20.00	('Successfully downloaded', 'train-images-idx3-ubyte.gz', 9912422, 'bytes.')
1.64/20.63	('Successfully downloaded', 'train-labels-idx1-ubyte.gz', 28881, 'bytes.')
1.66/25.13	('Successfully downloaded', 't10k-images-idx3-ubyte.gz', 1648877, 'bytes.')
1.66/25.58	('Successfully downloaded', 't10k-labels-idx1-ubyte.gz', 4542, 'bytes.')
2.08/26.05	Traceback (most recent call last):
2.08/26.05	  File "../convolutional-hpolib.py", line 385, in <module>
2.08/26.05	    result = main(params, **args)
2.08/26.05	  File "../convolutional-hpolib.py", line 376, in main
2.08/26.05	    y = train_mnist(dataset, flags)
2.08/26.05	  File "../convolutional-hpolib.py", line 231, in train_mnist
2.08/26.05	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
2.08/26.05	ValueError: invalid literal for int() with base 10: '8.0'
